/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'szpak' at '8/17/16 11:16 AM' with Gradle 2.13
 *
 * @author szpak, @date 8/17/16 11:16 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
