/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'szpak' at '8/17/16 11:16 AM' with Gradle 2.13
 *
 * @author szpak, @date 8/17/16 11:16 AM
 */
import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

import java.time.Duration
import java.time.Instant

class LibraryTest extends Specification{

    def "should reproduce performance regression in Gradle 2.14"() {
        expect:
            Instant starts = Instant.now();
            ProjectBuilder.builder().build()
            println "ProjectBuilder built time: ${Duration.between(starts, Instant.now())}"
    }
}
